name: Lint

on: 
  push:
    branches: 
      - continuous_deployment

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
    - run: npm install
    - run: npm run css-lint
